# gosec configuration for ACR
# These exclusions are for legitimate CLI operations, not security vulnerabilities

global:
  # Exclude rules that flag normal CLI tool operations
  excludes:
    # G204: Subprocess launched with variable - required for executing codex/gh CLIs
    - G204
    # G301: Directory permissions - Go's default 0755 is appropriate for temp worktrees
    - G301
    # G304: File path provided as taint input - required for reading config files
    - G304
    # G306: WriteFile permissions - not currently used but exclude for consistency
    - G306
